### ISSUE TITLE
[Bug] Can not begin to work issue

### ISSUE THREAD

**Issue by Kristinita** [erbridge/CodeWrapper#1]
### Summary

I can not begin to work use CodeWrapper.
### Expected behavior

Wrap my code.
### Actual behavior

``` python
command: code_wrapper
Traceback (most recent call last):
  File "E:\Sublime Text Build 3126 For Debug\sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "code_wrapper in E:\Sublime Text Build 3126 For Debug\Data\Installed Packages\CodeWrapper.sublime-package", line 44, in run
  File "code_wrapper in E:\Sublime Text Build 3126 For Debug\Data\Installed Packages\CodeWrapper.sublime-package", line 67, in _get_commands
AttributeError: 'NoneType' object has no attribute 'get'
```
### Steps to reproduce

I tested on a version of Sublime Text without plugins and user settings.

I install plugin → I restart Sublime Text → I select fragments of my PHP or Python codes → <kbd>Ctrl+Shift+P</kbd> → `CodeWrapper` → I get stack trace.
### Environment

**Operating system and version:**
Windows 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by erbridge** [comment]
Thanks for the report. Should be fixed when you next update.

**Comment by Kristinita** [comment]
@erbridge , thank you! Now I no get stack trace. Please, can you add in `README.MD` manual about usage your plugin? If you add screencasts, it's be good. I select my codes, run command `code_wrapper`, but nothing happens.

**Comment by erbridge** [comment]
I suggest you take a look at the `sublime-settings` file. I doubt I'll get time to add more instructions, sorry.
